ESFDC/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Material_Item__c</fullName>
        <label>Material Item</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ESFDC/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Brands_Page_URL__c</fullName>
        <label>Brands Page URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ESFDC/src/classes/Ctrl_MainCart.cls
public with sharing class Ctrl_MainCart {
  public List<Contact> contacts { get; set; }
    public String name { get; set; }
    public String Pname { get; set; }
    public String scyState { get; set; }
    public List<Product__c> lstProducts {get;set;}
    //public List<Brand__c> lstBProducts {get;set;}
    public Integer selQty {get;set;}
    public integer identifier = 0;
    public Id buyserid{get; set;}
  //  global String cnameg {get;set;}
    public Ctrl_MainCart() {
        //lstProducts = [Select Id, Name, Price__c, Quantity__c,Brands_Page_URL__c from Brand__c];  
        lstProducts = [Select Id, Name ,Brands_Page_URL__c from Product__c];   
        buyserid = ApexPages.currentPage().getParameters().get('id'); 
        //cnameg.se = buyserid;
        //Session['CustomerN'] = buyserid;
        //lstBProducts = [Select Id, Material_Item__c from Brand__c];
        
    }
    
    public void searchProducts() {
        String srchQuery = scyState + '%';
        lstProducts = [Select Id, Name, Brands_Page_URL__c from Product__c where Name like :srchQuery];
       // lstBProducts =[Select Id, Material_Item__c from Brand__c where Name like :srchQuery];
    }
    public void reduceQuantity() {
        // Formula logic - Quantity__c = Quantity__c - selQty;
        // update products - DML
    }
}