ESFDC/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Availablity__c</fullName>
        <label>Availablity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Material_Item__c</fullName>
        <label>Material Item</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Quantity__c</fullName>
        <label>Selected Quantity</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ESFDC/src/objects/Buyer__c.object
<CustomObject>
    <label>Buyer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ESFDC/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Name</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buyed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Buyed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Buyer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer</label>
        <referenceTo>Buyer__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Order__c</fullName>
        <label>Date of Order</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Material_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material Item</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Orders (Brand)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ESFDC/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ESFDC/src/classes/Ctrl_ShoppingSearch.cls
public with sharing class Ctrl_ShoppingSearch
{

    public List<Contact> contacts { get; set; }
    public String name { get; set; }
    public String searchstate { get; set; }
    public String BsrchQuery {get; set;}
    public List<Brand__c> lstWProducts {get;set;}
    public List<Order__c> lstOrderedProducts {get;set;}
    public Integer selQty {get;set;}
    public integer identifier =0;
    public Id buyserid{get; set;}
    public Integer Errorcount;
    
    public Ctrl_ShoppingSearch() {
        BsrchQuery = ApexPages.currentPage().getParameters().get('id'); 
        buyserid = ApexPages.currentPage().getParameters().get('cname'); 
        String BQuery = BsrchQuery +'%';
        lstWProducts = [Select Id,Name,Cost__c ,Availablity__c ,Selected_Quantity__c from Brand__c where Material_Item__c =: BsrchQuery]; 
    }
    
      public PageReference Add2Cart() {
        Errorcount = 0;
        Brand__c myAcct;
        Order__c myorderlist;
        Set<String> nameSet = new Set<String>();
        List<Order__c> oderList1 = new List<Order__c>();
        for(Brand__c b:lstWProducts)
        {     
          if(b.Selected_Quantity__c!='0') {
          if(b.Availablity__c > Integer.valueOf(b.Selected_Quantity__c)){       
              nameSet.add(b.name);
              Order__c order = new Order__c();
              order .Brand__c= b.id;
              list<Buyer__c> buy2 =new list<Buyer__c> ();
              buy2=[select id from  Buyer__c where id=:buyserid];
              list<Product__c> Product2 =new list<Product__c> ();
              Product2=[select id from  Product__c where Name =:BsrchQuery];
              order.Name__c = Product2[0].id; 
              order.Buyer_Name__c=buy2[0].id;
              order.Quantity__c= Integer.valueOf(b.Selected_Quantity__c);
              order.Price__c =  b.Cost__c * Decimal.valueOf(b.Selected_Quantity__c);
              order.Date_of_Order__c = Datetime.now();
              order.Buyed__c = false;
              oderList1.add(order);
              b.Selected_Quantity__c = '0';
              Errorcount=0;
              }
                else{
                     ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Invalid Quantity')); 
                    Errorcount = Errorcount + 1;
                }
            }
               else{
                    ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'please select quantity')); 
                   Errorcount = Errorcount + 1;
               }
              }
        
       update lstWProducts;
       insert oderList1; 
      
       PageReference retURL = new PageReference('/apex/AddToCart?id='+buyserid);
       PageReference pageRef = ApexPages.currentPage();
      if(Errorcount == 0){
        retURL.setRedirect(true);
             return retURL;
         }
        else{             
            return null;
       }
    }
    
    
    public void searchProducts() {
        String srchQuery = searchstate + '%';
        lstWProducts = [Select Id, Name,Cost__c ,Availablity__c ,Selected_Quantity__c from Brand__c where Material_Item__c =: BsrchQuery and  Name like :srchQuery];
    }
    
    public PageReference reduceQuantity() {
        Errorcount = 0;
        System.debug(Errorcount);
        Brand__c myAcct;
        Order__c myorderlist;
        Set<String> nameSet = new Set<String>();
        List<Order__c> oderList = new List<Order__c>();
        for(Brand__c b:lstWProducts)
        {            
                  
            if(b.Selected_Quantity__c!='0') {
              if(b.Availablity__c > Integer.valueOf(b.Selected_Quantity__c)){
                  
              b.Availablity__c = b.Availablity__c-Decimal.valueOf(b.Selected_Quantity__c);
              nameSet.add(b.name);
              // b.Material_Item__c = BsrchQuery;
              Order__c order = new Order__c();
              order .Brand__c= b.id;
              list<Buyer__c> buy =new list<Buyer__c> ();
              buy=[select id from  Buyer__c where id=:buyserid];
              list<Product__c> Product1 =new list<Product__c> ();
              Product1=[select id from  Product__c where Name =:BsrchQuery];
              order.Name__c = Product1[0].id; 
              order.Buyer_Name__c=buy[0].id;
              system.debug(order.Name__c);
              //order .Quantity__c= Decimal.valueOf(b.Selected_Quantity__c);
              order.Quantity__c= Integer.valueOf(b.Selected_Quantity__c);
              order.Buyed__c = true;
              order.Price__c =  b.Cost__c * Decimal.valueOf(b.Selected_Quantity__c);
              order.Date_of_Order__c = Datetime.now();
              oderList .add(order);
              b.Selected_Quantity__c = '0';
              Errorcount=0;
              }
                else{
                     ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Invalid Quantity')); 
                    Errorcount = Errorcount + 1;
                }
            }
               else{
                    ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'please select quantity')); 
                   Errorcount = Errorcount + 1;
               }
        }  
        
       
       update lstWProducts;
       insert oderList; 
        
       // Insert myorderlist;
        PageReference retURL1 = new PageReference('/apex/OrderedList?id='+buyserid);
        if(Errorcount == 0){
        retURL1.setRedirect(true);
             return retURL1;
         }
        else{             
             return null;
       }
  
    }
}